### ISSUE TITLE
[commander-1] process has died

### ISSUE THREAD

**Issue by sshetty1793** [bostoncleek/quadruped_control#1]
Hello,
I was trying to run this code on my ROS noetic setup. The build was successful and the robot was able to spawn on the drake environment. However, while running the "rosservice call /stand_up" service,  I keep running into this issue
![Screenshot from 2021-11-05 08-01-19](https://user-images.githubusercontent.com/84512826/140471507-bf15e2be-123a-4781-9593-5f3186679273.png)

After trying to find the cause of the issue, I found that the file "balance_controller.cpp" line 152 where the matrix multiplication of (A_dyn.t() * S_ * A_dyn + W_) is the source of the problem.
![Screenshot from 2021-11-05 08-11-36](https://user-images.githubusercontent.com/84512826/140472226-ed6c8dc7-25a0-402e-89cf-cc88f5d29f41.png)

The matrix multiplication A_dyn.t() * S_ is causing SEGMENTATION FAULT.
I checked the dimensions of the matrices and they all seem correct. Removing the S_ matrix will run the code with no errors. But the robot becomes unstable. Could you please give a reason for this?

**Comment by bostoncleek** [comment]
Hey,

I've seen this issue before. The solution is described in the [dependency](https://github.com/bostoncleek/quadruped_control#dependencies) section. Basically you just need to add those two lines to the qpOASES CMakeLists.txt file. 

If you did that and still have an issue post back here and I will help you resolve it.

However, I recommend using [osqp](https://osqp.org/) instead of qpOASES for many reasons. One of which it will alleviate the need to make the modification above. 

There will soon be a PR to introduce osqp but if you need this to work very soon I recommend writing your own osqp interface. You can take inspiration from drake [osqp_solver.cc](https://github.com/RobotLocomotion/drake/blob/master/solvers/osqp_solver.cc) and trajopt_ros [osqp_interface.cpp](https://github.com/tesseract-robotics/trajopt/blob/master/trajopt_sco/src/osqp_interface.cpp). This is totally optional and this repo will work fine with qpOASES.

**Comment by sshetty1793** [comment]
This worked. Thanks.

Although i see that the robot behaves abruptly after standing up. 
![simplescreenrecorder-2021-11-09_12 39 48](https://user-images.githubusercontent.com/84512826/140917987-1a1084c2-dbe2-4e49-b3ac-224e5a91a268.gif)

Is this because of the initial parameters from the mit_cheetah_config file?

**Comment by bostoncleek** [comment]
Sometimes it falls over but most of the time is should work properly. 

Is it falling over every time it stands up?

One thing to try is to increase the control frequency to 500 in `mit_cheetah_config`.

**Comment by bostoncleek** [comment]
Are you commanding it to walk just as it stands? If so let it reach the standing height for a few seconds before walking.

**Comment by sshetty1793** [comment]
The robot falls over every single time.
I tried increasing the control frequency. Still the same result. 
I am just calling the rosservice _/stand_up_. 

Did a little debugging and it looks like the foothold positions are not correct. The robot leans towards the right every time because of this.

**Comment by bostoncleek** [comment]
I recall having this same issue before. I'll take a look after work. It had something to do with timing.

**Comment by bostoncleek** [comment]
Can you tell me more about the foot positions not be correct?

**Comment by bostoncleek** [comment]
I just test this several times and I see it working. 

I did however encounter an issue where it was falling over a lot. The issue was due to the message frequency. The topic `joint_torque_cmd` should be at 300Hz and `com_state` should be around 600Hz. 

Can you verify the frequency of these messages?

https://user-images.githubusercontent.com/36201047/141207625-564366eb-c146-4ef1-ab2b-181b5926e482.mp4

**Comment by bostoncleek** [comment]
I replicated this issue. When director connects to drake it typically slows the rate at which state info is published on `com_state` but depending on your cpu the state info may be sent either too quickly or too slowly. So I added a parameter to set a fixed rate on  `drake_interface_node`. If you pull from master and rebuild it should work. Please let me know if it does not.

**Comment by sshetty1793** [comment]
The  new changes fixed the issue. Thanks :+1:
